### ISSUE TITLE
controller in high availability mode

### ISSUE THREAD

**Issue by mskitroot** [IBM/ibm-block-csi-operator#406]
Is there a way to define that the controller stateful set has two or more controllers?

Is there a reason why only one is spawned thus losing the controller during draining or node restarts/failures

**Comment by mskitroot** [comment]
Thanks @kasserater I understand the operator. What I am looking for is HA on the controller.

The Controller CR does not provide any input to launch a HA stateful set and I was wondering how we could do that?

If the node hosting the controller is down even for that brief time then while it starts up again no actions are taken when it comes to PVCs.

This is the extract of the resource.

```
apiVersion: csi.ibm.com/v1
kind: IBMBlockCSI
metadata:
  name: ibm-block-csi
  labels:
    app.kubernetes.io/name: ibm-block-csi
    app.kubernetes.io/instance: ibm-block-csi
    app.kubernetes.io/managed-by: ibm-block-csi-operator
    release: v1.12.1
spec:
  # controller is a statefulSet with ibm-block-csi-controller container
  # and csi-provisioner, csi-attacher, csi-snapshotter and livenessprobe sidecars.
  controller:
    repository: quay.io/ibmcsiblock/ibm-block-csi-driver-controller
    tag: "1.12.0"
    imagePullPolicy: IfNotPresent
```

Looking at the IBMBlockCSI CustomResource I could not find how to tell the operator to launch an HA stateful set. Is that something that is supported or in the plan?

Thanks
